services:
  db:
    image: postgres:16-alpine
    container_name: applyr-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: applyr
      POSTGRES_PASSWORD: applyr_pass
      POSTGRES_DB: applyr_db_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./server
      dockerfile: /src/Applyr.Api/Dockerfile
    container_name: applyr-api-dev
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5000:8080"

volumes:
  pgdata: